export const caruselArray = [
    {
        id: 1,
        title: "Финансовые консультации по инвестированию",
        subtitle: "Акции компаний США",
        site: "azmuth-mo.ru",
        category: "Реклама",
        images: [{ url: "/images/carusel/azimuth1200.webp" }],
        link: "https://azimuth-mo.ru/",
    },
    {
        id: 2,
        title: "Денежные переводы Россия-Турция",
        subtitle: "низкий курс",
        site: "money_transfer.ru",
        category: "Реклама",
        images: [{ url: "/images/carusel/transfer_money.webp" }],
        link: "/product/6618fad69d48ccae6816845e",
    },
    {
        id: 3,
        title: "Реклама Ваших продуктов в Кемере",
        subtitle: "от ₺100 в месяц",
        site: "kemer.app",
        category: "Реклама",
        images: [{ url: "/images/carusel/kemer-online.webp" }],
        link: "/start",
    },
    {
        id: 4,
        title: "Место для Вашей рекламы",
        subtitle: "от ₺100 в месяц",
        site: "site.com",
        category: "Реклама",
        images: [{ url: "/images/carusel/default_carusel.webp" }],
        link: "#",
    },
    {
        id: 5,
        title: "Реклама в GOOGLE",
        subtitle: "от ₺100 в месяц",
        site: "site.com",
        category: "Реклама",
        images: [{ url: "/images/carusel/googleReclam.webp" }],
        link: "#",
    },
];
