export const reclamArray = [
    {
        id: 1,
        name: "Финансовые консультации по инвестированию",
        subtitle: "Акции компаний США",
        site: "azmuth-mo.ru",
        category: "Реклама",
        images: [{ url: "/images/reclam/azimuth1200.webp" }],
        link: "https://azimuth-mo.ru/",
    },
    {
        id: 2,
        name: "Colefor",
        subtitle: "",
        site: "colefor.com",
        category: "Реклама",
        images: [{ url: "/images/reclam/colefor_reclam.webp" }],
        link: "/product/66179550f9abd2efcefd96f6",
    },
    {
        id: 3,
        name: "Денежные переводы Россия-Турция",
        subtitle: "низкий курс",
        site: "money_transfer.ru",
        category: "Реклама",
        images: [{ url: "/images/reclam/transfer_money.webp" }],
        link: "/product/6618fad69d48ccae6816845e",
    },
    {
        id: 4,
        name: "Реклама Ваших продуктов в Кемере",
        subtitle: "от ₺100 в месяц",
        site: "kemer.app",
        category: "Реклама",
        images: [{ url: "/images/reclam/kemer-online.webp" }],
        link: "/start",
    },
    {
        id: 5,
        name: "Место для Вашей рекламы",
        subtitle: "от ₺100 в месяц",
        site: "kemer.app",
        category: "Реклама",
        images: [{ url: "/images/reclam/default_reclam.webp" }],
        link: "#",
    },
];
